// Keep this list at 30 or fewer entries while the demonstration uses Primat's
// daily-limited demo endpoint. Add new product classes or verified brands here.
export const PRIMAT_DISCOVERY_QUERIES = [
  "snus",
  "nikotin",
  "nikotinpåsar",
  "tobak",
  "vitt snus",
  "portionssnus",
  "cigaretter",
  "rulltobak",
  "vape",
  "e-cigarett",
  "e-cigg",
  "pod",
  "velo",
  "zyn",
  "loop",
  "xqs",
  "helwit",
  "kelly white",
  "skruf",
  "knox",
  "general",
  "lundgrens",
  "ettan",
  "grov",
  "vont",
  "vuse",
  "elf bar",
  "lost mary",
  "rev pod",
  "nicorette",
] as const;
