/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as SearchRouteImport } from './routes/search'
import { Route as MapIdRouteImport } from './routes/map.$id'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as ApiPublicGmapsRouteImport } from './routes/api/public/gmaps'
import { Route as ApiPublicPrimatProductsRouteImport } from './routes/api/public/primat-products'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const MapIdRoute = MapIdRouteImport.update({
  id: '/map/$id',
  path: '/map/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGmapsRoute = ApiPublicGmapsRouteImport.update({
  id: '/api/public/gmaps',
  path: '/api/public/gmaps',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPrimatProductsRoute = ApiPublicPrimatProductsRouteImport.update({
  id: '/api/public/primat-products',
  path: '/api/public/primat-products',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/favorites': typeof FavoritesRoute
  '/search': typeof SearchRoute
  '/map/$id': typeof MapIdRoute
  '/product/$id': typeof ProductIdRoute
  '/api/public/gmaps': typeof ApiPublicGmapsRoute
  '/api/public/primat-products': typeof ApiPublicPrimatProductsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/favorites': typeof FavoritesRoute
  '/search': typeof SearchRoute
  '/map/$id': typeof MapIdRoute
  '/product/$id': typeof ProductIdRoute
  '/api/public/gmaps': typeof ApiPublicGmapsRoute
  '/api/public/primat-products': typeof ApiPublicPrimatProductsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/favorites': typeof FavoritesRoute
  '/search': typeof SearchRoute
  '/map/$id': typeof MapIdRoute
  '/product/$id': typeof ProductIdRoute
  '/api/public/gmaps': typeof ApiPublicGmapsRoute
  '/api/public/primat-products': typeof ApiPublicPrimatProductsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/favorites'
    | '/search'
    | '/map/$id'
    | '/product/$id'
    | '/api/public/gmaps'
    | '/api/public/primat-products'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/favorites'
    | '/search'
    | '/map/$id'
    | '/product/$id'
    | '/api/public/gmaps'
    | '/api/public/primat-products'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/favorites'
    | '/search'
    | '/map/$id'
    | '/product/$id'
    | '/api/public/gmaps'
    | '/api/public/primat-products'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  FavoritesRoute: typeof FavoritesRoute
  SearchRoute: typeof SearchRoute
  MapIdRoute: typeof MapIdRoute
  ProductIdRoute: typeof ProductIdRoute
  ApiPublicGmapsRoute: typeof ApiPublicGmapsRoute
  ApiPublicPrimatProductsRoute: typeof ApiPublicPrimatProductsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map/$id': {
      id: '/map/$id'
      path: '/map/$id'
      fullPath: '/map/$id'
      preLoaderRoute: typeof MapIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/gmaps': {
      id: '/api/public/gmaps'
      path: '/api/public/gmaps'
      fullPath: '/api/public/gmaps'
      preLoaderRoute: typeof ApiPublicGmapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/primat-products': {
      id: '/api/public/primat-products'
      path: '/api/public/primat-products'
      fullPath: '/api/public/primat-products'
      preLoaderRoute: typeof ApiPublicPrimatProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  FavoritesRoute: FavoritesRoute,
  SearchRoute: SearchRoute,
  MapIdRoute: MapIdRoute,
  ProductIdRoute: ProductIdRoute,
  ApiPublicGmapsRoute: ApiPublicGmapsRoute,
  ApiPublicPrimatProductsRoute: ApiPublicPrimatProductsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
